### ISSUE TITLE
x-terminal 11.0.2 does not open

### ISSUE THREAD

**Issue by softwarecreations** [bus-stop/x-terminal#187]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [x] I have tried uninstalling/reinstalling the terminal.
- [ ] I have not tried uninstalling/reinstalling the terminal.
### Workaround
1. Uninstall x-terminal
2. Close atom
3. `apm install x-terminal@11.0.1`
4. (it works)
5. Don't update to 11.0.2

### Description
X-terminal doesn't open, neither by key-binding (KeyBindingResolver shows the keybinding works) nor by opening it with the Atom menu Packages > X-Terminal > Open new terminal.
Literally nothing happens.
No error is shown in the Atom inspector's console tab.
However when I open Atom's inspector's console tab, it shows the error
"Failed to require the main module of 'x-terminal' because it requires one or more incompatible native modules (node-pty-prebuilt-multiarch).
Run `apm rebuild` in the package directory and restart Atom to resolve."

I have
1. Closed atom
2. Open a (real) terminal
3. `cd ~/.atom/packages`
4. `apm rebuild`
5. It says: `Rebuilding modules ✓`

I have
1. Closed atom
2. Open a (real) terminal
3. `cd ~/.atom/packages/x-terminal`
4. `apm rebuild`
5. It says: `Rebuilding modules ✓`

No change.

### Steps to reproduce
1. Try open x-terminal

**Expected behavior:**
Terminal opens.

**Actual behavior:**
Nothing happens, no error is displayed on screen or in the atom inspector's console.

**Reproduces how often:**
100% of the time

### Versions
Atom    : 1.52.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.52.0
python 2.7.16
git 2.20.1
x-terminal: 11.0.2
OS: Linux
Debian 10 Buster
Linux kernel: Backported 5.8

### Additional context
I've been using x-terminal for many weeks, suddenly it won't open, if I recall correctly it broke immediately after an update.

**Comment by the-j0k3r** [comment]
This is to be expected, Atom 1.51.x uses Electron 5.x node-pty-prebuilt` version while Atom 1.52.x uses Electron: 6.1.12, so the issue is on an x-terminal update which is APM/GYP domain, it clearly theres an issue with those Atom packages, FYI we have no control over.

So you really have to uninstall and reinstall x-terminal for better results, ennsuring the correct version of node-pty-prbuilt is installed for the correct electron version of Atom.

Should work :tm: famous last words.

The difference between `x-terminal@11.0.1` and `x-terminal@11.0.2` should not have any bearing on node-pty-prebuilt versions installed.

**Comment by softwarecreations** [comment]
@the-j0k3r thanks for responding.

> So you really have to uninstall and reinstall x-terminal for better results, ennsuring the correct version of node-pty-prbuilt is installed for the correct electron version of Atom.

As I noted in the bug report above, I've tested uninstalling and reinstalling x-terminal, but it didn't work.

So just to be sure I tried that again now, with the **exact** same results as the above.

1. Uninstall x-terminal.
2. Close Atom.
3. Open Atom.
4. Install x-terminal
5. Note the error https://github.com/bus-stop/x-terminal/issues/188#issuecomment-709937631 in the Atom console inspector, it's broken.
6. Closed atom, tried the rebuild. Same as before. Says it rebuilt but terminal has same (not working) issue.
7. Open atom, uninstall x-terminal, close Atom.
8. apm install x-terminal@11.0.1
9. Open Atom and test: It works
10. Don't update to 11.0.2

> The difference between `x-terminal@11.0.1` and `x-terminal@11.0.2` should not have any bearing on node-pty-prebuilt versions installed.

Makes all the difference for me.

Just sharing my experience for others to potentially benefit from.

Thanks for everything you do for this project :)

**Comment by the-j0k3r** [comment]
The issue is because you have upgraded Atom from 1.51.0 with electron 5.1.13 to Atom 1.52.0 with electron 6.1.12, the x-terminal versions issue is a false positive because:

1) There are 0 commits between x-terminal 11.0.1 and 11.0.2 that affect `node-pty-prebuilt-multiarch` or the way its installed.

Each electron version requires corresponding  version specific `node-pty-prebuilt-multiarch` binaries, because somehow your system is not installing the correct `node-pty-prebuilt-multiarch` binaries your error persists.

The packages responsible for installing/upgrading Atom addons are https://github.com/atom/apm, and in turn node-gyp is responsible for rebuilding any modules like `node-pty-prebuil-multiarch` there are several issues with both apm and node-gyp. Failures to properly do their tasks result in failed addon upgrades with bizarre errors and results.

The uninstall and re-install ensures that the proper corresponding electron 6.1.12 `node-pty-prebuilt-multiarch` binaries are installed.

To confirm the issue is not with x-terminal 11.0.2 do the following with Atom closed.

1) delete `~\.atom\packages\x-terminal` manually
2) open a terminal and type `apm install xterminal@11.0.2` 
3) open atom and test a terminal.

If it doesnt work: close Atom.

1) download [node-pty-prebuilt-multiarch.zip](https://github.com/bus-stop/x-terminal/files/5397233/node-pty-prebuilt-multiarch.zip)
2) delete your `~/.atom/packages/x-terminal/node_modules/node-pty-prebuilt-multiarch`
3) unzip the downloaded to `~/.atom/packages/x-terminal/node_modules/`
4) open Atom and test a terminal.

The node-pty-prebuilt-multiarch come from a new fresh install of ubuntu 18.04 lts and atom 1.52.0 with x-terminal 11.0.2

If you dont want to use that, download the corresponding binaries from https://github.com/oznu/node-pty-prebuilt-multiarch/releases.

You're looking for electron 6.x corresponding abi.

https://github.com/lgeiger/node-abi/blob/master/abi_registry.json#L27-L31

I thinks its this https://github.com/oznu/node-pty-prebuilt-multiarch/releases/download/v0.9.0/node-pty-prebuilt-multiarch-v0.9.0-electron-v73-linux-x64.tar.gz but double check.

**Comment by softwarecreations** [comment]
Wow @the-j0k3r I really didn't expect you to put so much effort into this.

My main concern is that the terminal works. Since it's not (too) broken, I'm not going to spend more time "fixing" it right now.

Perhaps if it doesn't clear up I'll try manual workarounds that you mentioned.
Maybe there's a bug somewhere that'll get resolved soon.

> To confirm the issue is not with x-terminal 11.0.2 do the following with Atom closed.
> 
>     1. delete `~\.atom\packages\x-terminal` manually
> 
>     2. open a terminal and type `apm install xterminal@11.0.2`
> 
>     3. open atom and test a terminal.

I did this, same results
```
# close atom
~/.atom/packages$ rm -rf x-terminal/
~/.atom/packages$ apm install x-terminal@11.0.2
Installing x-terminal@11.0.2 to ~/.atom/packages ✓
# started atom, terminal broken, closed atom
~/.atom/packages$ rm -rf x-terminal/
~/.atom/packages$ apm install x-terminal@11.0.1
Installing x-terminal@11.0.1 to ~/.atom/packages ✓
# opened atom, terminal works
```

So going to settle for 11.0.1 for now.

**Comment by the-j0k3r** [comment]
So you did not try the binaries I suggested.

>So going to settle for 11.0.1 for now.

>Wow @the-j0k3r I really didn't expect you to put so much effort into this.

I put effort into this, because settling for a specific x-terminal version is not a good idea because of some error that only happens in your system, if something security wise or a bug gets fixed you're missing out and left out. I put effort into it, because its better to get to the root of the problem no matter what.

For good measure, clear any stale caches for node and other components, Also look at install logs for anything related to `node-pty-prebuilt-multiarch`, this could have some clews to the issue.

> I'm not going to spend more time "fixing" it right now.

I can understand your choice, so Ive left above some things that you could try when you get back to this.

One thing I would like you to try is installing https://github.com/bus-stop/terminus and disabling x-terminal and see if terminus works. Less than 2 minutes on that would shed some light into this.

Good luck and until next time.

**Comment by softwarecreations** [comment]
Thanks for your reply @the-j0k3r 
To test your idea, I've uninstalled x-terminal and installed terminus. It's working fine.

Just to see what would happen, I tried installing the latest version of x-terminal while terminus is installed and running, but got the same issue for x-terminal as above.
Then I uninstalled x-terminal, used apm to install 11.0.1 and restarted atom. So I can run terminus and x-terminal@11.0.1 simultaneously, and they both work, showing on screen at the same time.

**Comment by the-j0k3r** [comment]
> To test your idea, I've uninstalled x-terminal and installed terminus. It's working fine.

Uses same `node-pty-prebuilt-multiarch` for electron 6.x so that's strange, also this terminus/node_modules/node-pty-prebuilt-multiarch directory you could copy to the x-terminal@11.0.2/node_modules/node-pty-prebuilt-multiarch dir

Also not a good idea to run both terminals  Pick one and stick to it by disabling one of them.

**Comment by softwarecreations** [comment]
Thanks, will give it a try soon, hopefully tomorrow, enough shenanigans for the day need to get some work done :)

**Comment by softwarecreations** [comment]
@the-j0k3r I updated to 11.0.3 (normally) and it's working now `>.<` haha

**Comment by the-j0k3r** [comment]
> @the-j0k3r I updated to 11.0.3 (normally) and it's working now `>.<` haha

Like I said. its in your head.

**Comment by softwarecreations** [comment]
So you want to bet that if I `apm install x-terminal@11.0.2` on my system it will work, and I'm just imagining that it doesn't work.
Cool, let's wager. $1000?

Jokes aside, thanks for your help.

**Comment by the-j0k3r** [comment]
If there is any issue, is with APM / node-gyp, not this package, the bump in version is another false positive.

I would have liked to get to the bottom of this, because apm/node-gyp should have proper bug reports about these issues it causes. So far across 4 similar projects thers is no real info to pinpoint where failures are ocurring in the installation phase or why.

Youre welcome though. Didnt do anything special either =)
